---
#- name: finding masters
#  debug: msg= "{{ hostvars[item]['ansible_host'] }}" 
#  with_items:
#    - "{{ groups['master'] }}"

- name: sethostname
  shell: |
    hostnamectl set-hostname "{{inventory_hostname}}.nomad.net"
  when: ansible_hostname != inventory_hostname
  register: hostname
  
- name: disable selinux
  selinux:
     state: disabled
  register: selinux


- name: Restart server 
  shell: sleep 1;dnf update ; reboot;sleep 1
  async: 1
  poll: 0
  ignore_errors: true
  when: hostname.changed or selinux.changed
  #  #
  #- name: Wait for server to restart
  #  local_action: wait_for  port= 22  delay= 1 timeout= 300
  #
  #
- name: Wait for restart
  wait_for_connection:
    delay: 20
    timeout: 240 
  when: hostname.changed or selinux.changed

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Restart server 
  shell: sleep 1;dnf update ; reboot;sleep 1
  async: 1
  poll: 0
  ignore_errors: true
  when: hostname.changed
  #  #
  #- name: Wait for server to restart
  #  local_action: wait_for  port= 22  delay= 1 timeout= 300
  #
  #
- name: Wait for restart
  wait_for_connection:
    delay: 20
    timeout: 240 
  when: hostname.changed
  #  
  #  
  #- name: disable some services
  #  systemd:
  #      name: "{{ item.name }}"
  #      state: stopped
  #      enabled: "{{ item.enabled }}"
  #      masked: "{{ item.masked }}"
  #  with_items:
  #      - {name: firewalld , enabled: yes, masked: yes }
  #      - {name: iptables, enabled: no, masked: no}
  #  
