---


- name:  adding NetworkManager config
  template:
    src: localdns.conf.j2
    dest: /etc/NetworkManager/conf.d/localdns.conf

- name: create netmasq config file
  file: path=/etc/NetworkManager/dnsmasq.d/libvirt_dnsmasq.conf  owner=root group=root mode=755 state=touch


- name: adding libvirt_dnsmasq.conf
  lineinfile:
    path: /etc/NetworkManager/dnsmasq.d/libvirt_dnsmasq.conf
    line: "server=/nomad.net/192.168.125.1"
