---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - dns

- hosts: nomad-master
  become: yes
  roles:
    - common
    - add-tools
    - consul
    - nomad


- hosts: nomad-node
  become: yes
  roles:
    - common
    - add-tools
    - consul
    - nomad
    - docker
    - java
    - rkt

- hosts: nomad-node0
  become: yes
  roles:
    - consul2dns
